{% set version = '2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rangebuilder
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rangeBuilder_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rangeBuilder/rangeBuilder_{{ version }}.tar.gz
  sha256: fceee76e8ee2841261a49b4a36c8966224913def895acd3a15d42dee6acd02e5

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # This is needed to suppress a warning about R.dll not being found
  missing_dso_whitelist:
    - '*/R.dll'            # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.12.9
    - r-alphahull >=2.5
    - r-pbapply
    - r-rnaturalearth
    - r-sf
    - r-stringi
    - r-terra
    - r-units
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.9
    - r-alphahull >=2.5
    - r-pbapply
    - r-rnaturalearth
    - r-sf
    - r-stringi
    - r-terra
    - r-units

test:
  commands:
    - $R -e "library('rangeBuilder')"           # [not win]
    - "\"%R%\" -e \"library('rangeBuilder')\""  # [win]

about:
  home: https://github.com/ptitle/rangeBuilder
  license: GPL-3.0-or-later
  summary: Provides tools for filtering occurrence records, generating alpha-hull-derived range
    polygons and mapping species distributions.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: rangeBuilder
# Type: Package
# Title: Occurrence Filtering, Geographic Standardization and Generation of Species Range Polygons
# Version: 2.1
# Authors@R: person("Pascal", "Title", email = "ptitle@umich.edu", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6316-0736"))
# Imports: alphahull (>= 2.5), stringi, sf, terra, pbapply, units, rnaturalearth, methods, Rcpp (>= 0.12.9)
# Depends: R (>= 3.5.0)
# Description: Provides tools for filtering occurrence records, generating alpha-hull-derived range polygons and mapping species distributions.
# License: GPL (>= 3)
# URL: https://github.com/ptitle/rangeBuilder
# BugReports: https://github.com/ptitle/rangeBuilder/issues
# NeedsCompilation: yes
# LinkingTo: Rcpp
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# ByteCompile: true
# Packaged: 2023-03-03 14:57:49 UTC; pascaltitle
# Author: Pascal Title [aut, cre] (<https://orcid.org/0000-0002-6316-0736>)
# Maintainer: Pascal Title <ptitle@umich.edu>
# Repository: CRAN
# Date/Publication: 2023-03-03 15:40:02 UTC
